name: aws cred test
description: validate terraform files


runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::565371312234:role/github-action-for-infra
        role-session-name: foo-bar
        aws-region: us-east-1
