name: aws cred test

on:
  workflow_dispatch

jobs:
  foo:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dep

